#!/bin/sh

# Git-Replace-Author : pre-receive hook
# P532 - Sub-project

# Made By: Ankit Sadana
# Username: asadana
# Made On: 12/17/2015

# Git Source Repository : git@github.com:asadana/Git-Check-Author.git

# Last Edited By: Ankit Sadana
# Username: asadana
# Last Edited On: 12/18/2015

# ============================================================

# The "pre-receive" script is runis invoked by git-receive-pack on the remote repository, which happens when a git push is done on a local repository. 
# Just before starting to update refs on the remote repository, the pre-receive hook is invoked. Its exit status determines the success or failure of the update.
#
# This hook executes once for the receive operation. It takes no arguments, but for each ref to be updated it receives on standard input a line of the format:
#
# <old-value> SP <new-value> SP <ref-name> LF
#
# where <old-value> is the old object name stored in the ref,
# <new-value> is the new object name to be stored in the ref
# and <ref-name> is the full name of the ref. When creating a new ref, <old-value> is 40 0.
#
# If the hook exits with non-zero status, none of the refs will be updated. If the hook exits with zero, updating of individual refs can still be prevented by the update hook.
# 
# Both standard output and standard error output are forwarded to git send-pack on the other end, so you can simply echo messages for the user.

# ============================================================

checkEmail() {
	# If condition checks if the authorEmail is available in the authorized_keys
	if [[ $(grep -w $authorEmail ~/.ssh/authorized_keys | wc -w) -gt 1 ]]; then
			# echo "Author Email: $authorEmail"
			echo
		else
			echo "##########################################"
			echo "You are using an unauthorized email."
			echo "Expected commit author format: IU-ID <IU-ID@indiana.edu>"
			echo "Please configure your git user.email to IU-email used to generate the SSH-key."
			echo "You can fix your email using: git config user.email IU-ID@indiana.edu"
			echo "Then fix the last commit with: git commit --amend --reset-author"
			echo "##########################################"
			exit 1
	fi	
}

checkName() {
	# Retrieving the author name from SHA-1 (newsha)
	authorName=$(git log -1 --pretty=format:%an $newsha)
	# Triming the authorEmail for the username
	expectedName=${authorEmail%@*}

	# If condition compares authorName and expectedName
	if [[ $authorName == $expectedName ]]; then
			# echo "Author Name: $authorName"
			exit 0
		else
			echo "Author Name found: $authorName"
			echo "Expected Name : $expectedName"

			echo "##########################################"
			echo "You are using wrong name for commits."
			echo "Expected commit author format: IU-ID <IU-ID@indiana.edu>"
			echo "Please configure your git user.name to IU-ID used to generate the SSH-key."
			echo "You can fix your name using: git config user.name IU-ID"
			echo "Then fix the last commit with: git commit --amend --reset-author"
			echo "##########################################"
			exit 1
	fi

}

# While loop reads the input from given to pre-receive when it is triggered
while read oldsha newsha refname; do
	# Retrieving the author email from SHA-1 (newsha)
	authorEmail=$(git log -1 --pretty=format:%ae $newsha)
	checkEmail
	checkName
done


