#!/bin/sh


# Git-Replace-Author : pre-receive hook
# P532 - Sub-project

# Made By: Ankit Sadana
# Username: asadana
# Made On: 12/17/2015

# Last Edited By: Ankit Sadana
# Username: asadana
# Last Edited On: 12/17/2015

# Source : git@github.com:asadana/Git-Replace-Author.git

# ============================================================

# The "pre-receive" script is runis invoked by git-receive-pack on the remote repository, which happens when a git push is done on a local repository. 
# Just before starting to update refs on the remote repository, the pre-receive hook is invoked. Its exit status determines the success or failure of the update.
#
# This hook executes once for the receive operation. It takes no arguments, but for each ref to be updated it receives on standard input a line of the format:
#
# <old-value> SP <new-value> SP <ref-name> LF
#
# where <old-value> is the old object name stored in the ref,
# <new-value> is the new object name to be stored in the ref
# and <ref-name> is the full name of the ref. When creating a new ref, <old-value> is 40 0.
#
# If the hook exits with non-zero status, none of the refs will be updated. If the hook exits with zero, updating of individual refs can still be prevented by the update hook.
# 
# Both standard output and standard error output are forwarded to git send-pack on the other end, so you can simply echo messages for the user.

# ============================================================

checkEmail() {
	if [[ $(grep -w $authorEmail /u/softeng/.ssh/authorized_keys | wc -w) -gt 1 ]]; then
			echo "Author Email: $authorEmail"
			exit 0
		else
			echo "Unauthorized Email"
			exit 1
		fi	
}

# While loop reads the input from given to pre-receive when it is triggered
while read oldsha newsha refname; do
	authorEmail=$(git log -1 --pretty=format:%ae $newsha)
	checkEmail
done


